name: hrk_batteries
version: 0.5.0

description: >-
  A library to accumulate required dart helper and utility codes
repository: https://github.com/hrishikesh-kadam/hrk_batteries.dart
topics:
  - batteries
  - dart-batteries

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  
dev_dependencies:
  test: ^1.21.0
  hrk_analysis: '>=0.1.0 <1.0.0'
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
