name: hrk_batteries
version: 0.1.0-dev.2

description: >-
  A library to accumulate required dart helper and utility codes
repository: https://github.com/hrishikesh-kadam/hrk_batteries.dart
topics:
  - batteries
  - dart-batteries

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
